# © 2023 Fraunhofer-Gesellschaft e.V., München
#
# SPDX-License-Identifier: AGPL-3.0-or-later


# generate key pair on server with
# ssh-keygen -m PEM -t rsa -b 4096
# use "demo_key" as target file and no password
# add public key to authorized keys with
# cat demo_key.pub >> ~/.ssh/authorized_keys
# open private key file with
# nano demo_key
# and copy private key to a GitHub secret variable of the repository: SSH_PRIVATE_KEY
# also create the secrets REMOTE_USER, REMOTE_HOST, REMOTE_PORT, REMOTE_TARGET and
# apply corresponding values
name: build_and_deploy

on: [push]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
    - name: install node.js dependencies
      run: |
        cd micat
        npm install
    - name: build
      run: |
        cd micat
        npm run build --if-present
    - name: deploy
      uses: pressidium/lftp-mirror-action@v1
      with:
        # SFTP credentials
        # sshpass -p <password> sftp user@host
        host: ${{ secrets.SFTP_URL }}
        port: ${{ secrets.SFTP_PORT }}
        user: ${{ secrets.SFTP_USER }}
        pass: ${{ secrets.SFTP_PASSWORD }}
        # lftp settings
        #onlyNewer: true
        #settings: 'sftp:auto-confirm=yes'
        # Mirror command options
        localDir: './micat/dist'
        #remoteDir: '.' #/var/www/html/example.com/public'
        reverse: true
        #ignoreFile: '.lftp_ignore'
        options: '--verbose'
        